config/routes.rb
Rails.application.routes.draw do
  
  resources :impuesto_unicos
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'page/index'
  get '/index' => redirect('page/index')
  root 'page#index'

  resources :personals do
    collection do
      get :search
    end
  end

 
  resources :certificates
  resources :asignacion_familiars
  resources :topes_legales
  resources :indicador_economicos
  resources :liquidacions
  resources :users
  resources :personals
  resources :sindicatos
  resources :afps
  resources :liquidacions  
  resources :haberes
  resources :empresas
  resources :descuento_adicionals
  resources :asignacions
  resources :bonificacions
  resources :subcategoria
  resources :categoria
  resources :tipocontratos
  resources :bancos
  resources :isapres
  resources :centrocostos

end

app/models/indicador_economico.rb
class IndicadorEconomico < ActiveRecord::Base

  validates_presence_of :indicador
  validates_numericality_of :valor  
end

app/controllers/indicador_economicos_controller.rb
# = indicador_economicos_controller.rb
#
# Autor::   Diego Gonzalez Cuevas
#
# === Clase indicador_economicos_controller
# Clase creada para realizar el control de las acciones para datos de los indicadores
# economicos y los parametros permitidos en la clase.
#
# Definición de la clase indicador_economicos_controller compuesta por
# * metodo index
# * metodo new
# * metodo create
# * metodo update
# * metodo destroy
# * metodo authorize
# * set_indicador_economico
# * indicador_economico_params
class IndicadorEconomicosController < ApplicationController
  before_action :authorize
  before_action :set_indicador_economico, only: [:show, :edit, :update, :destroy]

  # GET /indicador_economicos
  # GET /indicador_economicos.json
  def index
    @indicador_economicos = IndicadorEconomico.all
  end

  # GET /indicador_economicos/1
  # GET /indicador_economicos/1.json
  def show
  end

  # GET /indicador_economicos/new
  def new
    @indicador_economico = IndicadorEconomico.new
  end

  # GET /indicador_economicos/1/edit
  def edit
  end

  # POST /indicador_economicos
  # POST /indicador_economicos.json
  def create
    @indicador_economico = IndicadorEconomico.new(indicador_economico_params)

    respond_to do |format|
      if @indicador_economico.save
        format.html { redirect_to @indicador_economico, notice: 'Indicador economico creado exitosamente.' }
        format.json { render :show, status: :created, location: @indicador_economico }
      else
        format.html { render :new }
        format.json { render json: @indicador_economico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indicador_economicos/1
  # PATCH/PUT /indicador_economicos/1.json
  def update
    respond_to do |format|
      if @indicador_economico.update(indicador_economico_params)
        format.html { redirect_to @indicador_economico, notice: 'Indicador economico actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @indicador_economico }
      else
        format.html { render :edit }
        format.json { render json: @indicador_economico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indicador_economicos/1
  # DELETE /indicador_economicos/1.json
  def destroy
    @indicador_economico.destroy
    respond_to do |format|
      format.html { redirect_to indicador_economicos_url, notice: 'Indicador economico eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_indicador_economico
      @indicador_economico = IndicadorEconomico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def indicador_economico_params
      params.require(:indicador_economico).permit(:indicador, :valor)
    end
end

app/helpers/indicador_economicos_helper.rb
module IndicadorEconomicosHelper
end

app/views/indicador_economicos/_form.html.erb
<%= form_for(@indicador_economico) do |f| %>
  <% if @indicador_economico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@indicador_economico.errors.count, "error") %> prohibited this indicador_economico from being saved:</h2>

      <ul>
      <% @indicador_economico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :indicador %><br>
    <%= f.text_field :indicador %>
  </div>
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.text_field :valor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/indicador_economicos/edit.html.erb
<h3>Editando Indicador Económico</h3>

<%= render 'form' %>

<%= link_to 'Ver', @indicador_economico %> |
<%= link_to 'Volver', indicador_economicos_path %>

app/views/indicador_economicos/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Listando Indicadores económicos</h3>

<table>
  <thead>
    <tr>
      <th>Indicador</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @indicador_economicos.each do |indicador_economico| %>
      <tr>
        <td><%= indicador_economico.indicador %></td>
        <td>$<%= number_to_currency(indicador_economico.valor,strip_insignificant_zeros: true, :unit => "") %></td>
        <td><%= link_to 'Ver', indicador_economico %></td>
        <td><%= link_to 'Editar', edit_indicador_economico_path(indicador_economico) %></td>
        <td><%= link_to 'Eliminar', indicador_economico, method: :delete, data: { confirm: '¿Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Indicador economico', new_indicador_economico_path %>

app/views/indicador_economicos/new.html.erb
<h3>Nuevo Indicador Económico</h3>

<%= render 'form' %>

<%= link_to 'Volver', indicador_economicos_path %>

app/views/indicador_economicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Indicador:</strong>
  <%= @indicador_economico.indicador %>
</p>

<p>
  <strong>Valor:</strong>
  $<%= number_to_currency(@indicador_economico.valor,strip_insignificant_zeros: true, :unit => "") %>
</p>

<%= link_to 'Editar', edit_indicador_economico_path(@indicador_economico) %> |
<%= link_to 'Volver', indicador_economicos_path %>