config/routes.rb
Rails.application.routes.draw do
  
  resources :impuesto_unicos
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'page/index'
  get '/index' => redirect('page/index')
  root 'page#index'

  resources :personals do
    collection do
      get :search
    end
  end

 
  resources :certificates
  resources :asignacion_familiars
  resources :topes_legales
  resources :indicador_economicos
  resources :liquidacions
  resources :users
  resources :personals
  resources :sindicatos
  resources :afps
  resources :liquidacions  
  resources :haberes
  resources :empresas
  resources :descuento_adicionals
  resources :asignacions
  resources :bonificacions
  resources :subcategoria
  resources :categoria
  resources :tipocontratos
  resources :bancos
  resources :isapres
  resources :centrocostos

end

app/models/centrocosto.rb
class Centrocosto < ActiveRecord::Base
	has_many :personal, :dependent => :destroy
	validates_presence_of :nombre, :codigo, :detalle_centro

	before_save do |centros|
    	centros.nombre = centros.nombre.downcase.titleize
    end	
end

app/controllers/centrocostos_controller.rb
# = centrocostos_controller.rb
#
# Autor::   Diego Gonzalez Cuevas
#
# === Clase centrocostos_controller
# Clase creada para realizar el control de las acciones para datos de centros de
# costos y los parametros permitidos en la clase.
#
# Definición de la clase centrocostos_controller compuesta por
# * metodo index
# * metodo new
# * metodo create
# * metodo update
# * metodo destroy
# * metodo authorize
# * set_centrocosto
# * centrocosto_params
class CentrocostosController < ApplicationController
  before_action :authorize
  before_action :set_centrocosto, only: [:show, :edit, :update, :destroy]

  # GET /centrocostos
  # GET /centrocostos.json
  def index
    @centrocostos = Centrocosto.all
  end

  # GET /centrocostos/1
  # GET /centrocostos/1.json
  def show
  end

  # GET /centrocostos/new
  def new
    @centrocosto = Centrocosto.new
  end

  # GET /centrocostos/1/edit
  def edit
  end

  # POST /centrocostos
  # POST /centrocostos.json
  def create
    @centrocosto = Centrocosto.new(centrocosto_params)

    respond_to do |format|
      if @centrocosto.save
        format.html { redirect_to @centrocosto, notice: 'Centro de costos fue creado exitosamente.' }
        format.json { render :show, status: :created, location: @centrocosto }
      else
        format.html { render :new }
        format.json { render json: @centrocosto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /centrocostos/1
  # PATCH/PUT /centrocostos/1.json
  def update
    respond_to do |format|
      if @centrocosto.update(centrocosto_params)
        format.html { redirect_to @centrocosto, notice: 'Centro de costos fue actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @centrocosto }
      else
        format.html { render :edit }
        format.json { render json: @centrocosto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /centrocostos/1
  # DELETE /centrocostos/1.json
  def destroy
    @centrocosto.destroy
    respond_to do |format|
      format.html { redirect_to centrocostos_url, notice: 'Centro de costos fue eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_centrocosto
      @centrocosto = Centrocosto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def centrocosto_params
      params.require(:centrocosto).permit(:nombre, :codigo, :detalle_centro)
    end
end

app/helpers/centrocostos_helper.rb
module CentrocostosHelper
end

app/views/centrocostos/_form.html.erb
<%= form_for(@centrocosto) do |f| %>
  <% if @centrocosto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@centrocosto.errors.count, "error") %> prohibited this centrocosto from being saved:</h2>

      <ul>
      <% @centrocosto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="large-6 columns">
    <div class="field">
      <%= f.label :nombre %><br>
      <%= f.text_field :nombre %>
    </div>
  </div>
  <div class="large-6 columns">
    <div class="field">
      <%= f.label :codigo %><br>
      <%= f.text_field :codigo %>
    </div>
  </div>
  <div class="large-12 columns">
    <div class="field">
      <%= f.label :"Detalle" %><br>
      <%= f.text_field :detalle_centro %>
    </div>
  </div>
</div>




  <div class="actions">
    <%= f.submit ( f.object.new_record? ? "Crear" : "Actualizar"), class: "btn" %>
    <%= f.submit "Limpiar", :type => "reset" %>
  </div>

<% end %>

app/views/centrocostos/edit.html.erb
<h3>Editando Centro de costos</h3>

<%= render 'form' %>

<%= link_to 'Ver', @centrocosto %> |
<%= link_to 'Volver', centrocostos_path %>

app/views/centrocostos/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Listando Centros de costos</h3>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Codigo</th>
      <th>Detalle centro</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @centrocostos.each do |centrocosto| %>
      <tr>
        <td><%= centrocosto.nombre %></td>
        <td><%= centrocosto.codigo %></td>
        <td><%= centrocosto.detalle_centro %></td>
        <td><%= link_to 'Ver', centrocosto %></td>
        <td><%= link_to 'Editar', edit_centrocosto_path(centrocosto) %></td>
        <td><%= link_to 'Eliminar', centrocosto, method: :delete, data: { confirm: '¿Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Centro de costo', new_centrocosto_path %>

app/views/centrocostos/new.html.erb
<h3>Nuevo Centro de costos</h3>

<%= render 'form' %>

<%= link_to 'Volver', centrocostos_path %>

app/views/centrocostos/show.html.erb
<p id="notice"><%= notice %></p>

<table>
	<p>
	  <strong>Nombre:</strong>
	  <%= @centrocosto.nombre %>
	</p>

	<p>
	  <strong>Código:</strong>
	  <%= @centrocosto.codigo %>
	</p>

	<p>
	  <strong>Detalle centro:</strong>
	  <%= @centrocosto.detalle_centro %>
	</p>
</table>

<%= link_to 'Editar', edit_centrocosto_path(@centrocosto) %> |
<%= link_to 'Volver', centrocostos_path %>