config/routes.rb
Rails.application.routes.draw do
  
  resources :impuesto_unicos
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'page/index'
  get '/index' => redirect('page/index')
  root 'page#index'

  resources :personals do
    collection do
      get :search
    end
  end

 
  resources :certificates
  resources :asignacion_familiars
  resources :topes_legales
  resources :indicador_economicos
  resources :liquidacions
  resources :users
  resources :personals
  resources :sindicatos
  resources :afps
  resources :liquidacions  
  resources :haberes
  resources :empresas
  resources :descuento_adicionals
  resources :asignacions
  resources :bonificacions
  resources :subcategoria
  resources :categoria
  resources :tipocontratos
  resources :bancos
  resources :isapres
  resources :centrocostos

end

app/models/certificate.rb
class Certificate < ActiveRecord::Base
  belongs_to :personal, :dependent => :destroy



    MOTIVOS = ["Trámitar beneficios", "Trámites Judiciales ", "Trámites de asignación familiar", "Trámites internos", "Fines necesarios"]

end

app/controllers/certificates_controller.rb
# = certificates_controller.rb
#
# Autor::   Diego Gonzalez Cuevas
#
# === Clase certificates_controller
# Clase creada para realizar el control de las acciones para datos de certificados
# y los parametros permitidos en la clase.
# Si se ingresa como Empleado al sistema solo se puede hacer ingreso a index, show, update,
# y edit de certificates.
#
# Definición de la clase certificates_controller compuesta por
# * metodo index
# * metodo new
# * metodo create
# * metodo update
# * metodo destroy
# * metodo authorize
# * set_certificate
# * certificate_params
class CertificatesController < ApplicationController
  before_action :authorize, except: [:index,:show,:update,:edit]
  before_action :set_certificate, only: [:show, :edit, :update, :destroy]

  # GET /certificates
  # GET /certificates.json
  def index
    if current_user and current_user.tipo_usuario == "Administrador"
      @certificates= Certificate.all

    else
      @certificates=Certificate.where(rut_personal: current_user.rut_usuario)
    end
  end

  # GET /certificates/1
  # GET /certificates/1.json
  def show
    @certificate = Certificate.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
      pdf = CertificadoAntiguedadPdf.new(@certificate)
      send_data pdf.render, filename: "certificate #{@certificate}.pdf",
                            type: "application/pdf",
                            disposition: "inline"
      end
    end
  end

  # GET /certificates/new
  def new
    @certificate = Certificate.new
  end

  # GET /certificates/1/edit
  def edit
  end

  # Certificate /certificates
  # Certificate /certificates.json
  def create
    @certificate = Certificate.new(certificate_params)

    respond_to do |format|
      if @certificate.save
        format.html { redirect_to @certificate, notice: 'Certificado fue creado exitosamente.' }
        format.json { render :show, status: :created, location: @certificate }
      else
        format.html { render :new }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /certificates/1
  # PATCH/PUT /certificates/1.json
  def update
    respond_to do |format|
      if @certificate.update(certificate_params)
        format.html { redirect_to @certificate, notice: 'Certificado fue actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @certificate }
      else
        format.html { render :edit }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certificates/1
  # DELETE /certificates/1.json
  def destroy
    @certificate.destroy
    respond_to do |format|
      format.html { redirect_to certificates_url, notice: 'Certificado fue eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certificate
      @certificate = Certificate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def certificate_params
      params.require(:certificate).permit(:personal_id, :rut_personal, :motivo)
    end
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/views/certificates/_form.html.erb
<%= form_for(@certificate) do |f| %>
  <% if @certificate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@certificate.errors.count, "error") %> prohibited this certificate from being saved:</h2>

      <ul>
      <% @certificate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%if current_user%>
  <div class="field">
    <%= f.label :personal_id %><br>
    <%= collection_select(:certificate, :personal_id, Personal.all, :id, :nombre_apellido, include_blank: :true) %>
   </div>
  <div class="field">
    <%= f.label :rut_personal %><br>
    <%= f.text_field :rut_personal %>
  </div>
  <%else%>
    <div class="field">
    <%= f.label :personal_id %><br>
    <%= collection_select(:certificate, :personal_id, Personal.all, :id, :nombre_apellido, {},:disabled => "disabled") %>
   </div>
<% end %>
  <div class="field">
    <%= f.label :motivo %><br>
    <%= f.select :motivo, Certificate::MOTIVOS %>
  </div>
  <div class="actions">
    <%= f.submit ( f.object.new_record? ? "Crear" : "Actualizar"), class: "btn" %>
   </div>
<% end %>

app/views/certificates/edit.html.erb
<h3>Editando Certificados</h3>

<%= render 'form' %>

<%= link_to 'Ver', @certificate %> |
<%= link_to 'Volver', certificates_path %>

app/views/certificates/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Listando Certificados</h3>

<table>
  <%if @certificates.nil?%>
    <p>No encontrado los datos que requiere</p>
  <%else%>
  <thead>
    <tr>
      <th>Personal</th>
      <th>Motivo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @certificates.each do |certificate| %>
      <tr>
        <td><%= certificate.personal.nombre_apellido %></td>
        <td><%= certificate.motivo %></td>
        <td><%= link_to 'Ver', certificate %></td>
        <td><%= link_to 'Editar', edit_certificate_path(certificate) %></td>
        <%if current_user.tipo_usuario=="Administrador"%>
        <td><%= link_to 'Eliminar', certificate, method: :delete, data: { confirm: '¿Esta seguro?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
  <%end%>
</table>

<br>
<%if current_user.tipo_usuario=="Administrador"%>
<%= link_to 'Nuevo Certificado', new_certificate_path %>
<%end%>

app/views/certificates/new.html.erb
<h3>Nuevo Certificado</h3>

<%= render 'form' %>

<%= link_to 'Volver', certificates_path %>

app/views/certificates/show.html.erb
<p id="notice"><%= notice %></p>

<table>
	<p>
	  <strong>Personal:</strong>
	  <%= @certificate.personal.nombre_apellido %>
	</p>

	<p>
	  <strong>Motivo:</strong>
	  <%= @certificate.motivo %>
	</p>
</table>

<p>
<%= link_to "Certificado en PDF", certificate_path(@certificate, format: "pdf")%>
</p>
<%if current_user%>
<%= link_to 'Editar', edit_certificate_path(@certificate) %> |
<%end%>
<%= link_to 'Volver', certificates_path %>