config/routes.rb
Rails.application.routes.draw do
  
  resources :impuesto_unicos
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'page/index'
  get '/index' => redirect('page/index')
  root 'page#index'

  resources :personals do
    collection do
      get :search
    end
  end

 
  resources :certificates
  resources :asignacion_familiars
  resources :topes_legales
  resources :indicador_economicos
  resources :liquidacions
  resources :users
  resources :personals
  resources :sindicatos
  resources :afps
  resources :liquidacions  
  resources :haberes
  resources :empresas
  resources :descuento_adicionals
  resources :asignacions
  resources :bonificacions
  resources :subcategoria
  resources :categoria
  resources :tipocontratos
  resources :bancos
  resources :isapres
  resources :centrocostos

end

app/models/liquidacion.rb
class Liquidacion < ActiveRecord::Base
  belongs_to :asignacion
  belongs_to :habere
  belongs_to :bonificacion
  belongs_to :descuento_adicional
  belongs_to :personal

  validates :personal_id, presence: true
  validates :habere_id, presence: true
  validates_numericality_of :horas_trabajadas, :greater_than_or_equal_to => 50, :less_than_or_equal_to => 180, :message => "cantidad de horas incorrecta"
  validates :remuneracion, presence: true
  validates :cantidad_horas_extra, presence: true
  validates :horas_extra, presence: true
  validates :asignacion_id, presence: true
  validates :bonificacion_id, presence: true
  validates :vacaciones, presence: true
  validates :total_imponible, presence: true
  validates :porcentaje_afp, presence: true
  validates :descuento_afp, presence: true
  validates :cotizacion_voluntaria, presence: true
  validates :descuento_isapre, presence: true
  
  validates :sindicato, presence: true
  validates :impuesto, presence: true
  
  validates :desc_legales, presence: true
  validates :desc_varios, presence: true
  validates :liquido_pagar, presence: true
  validates :fecha_pago, presence: true

  def self.search(start_period, end_period)
    fecha =start_period.split("/")
    fecha_cambiada= ("#{fecha[2]}-#{fecha[1]}-#{fecha[0]}")
    start_period=fecha_cambiada
    fecha2 =end_period.split("/")
    fecha2_cambiada= ("#{fecha2[2]}-#{fecha2[1]}-#{fecha2[0]}")
    end_period=fecha2_cambiada
    where("fecha_pago between ? and ?", "#{start_period}", "#{end_period}")
  end

end

app/controllers/liquidacions_controller.rb
# = liquidacions_controller.rb
#
# Autor::   Diego Gonzalez Cuevas
#
# === Clase liquidacions_controller
# Clase creada para realizar el control de las acciones para datos de las liquidaciones
# y los parametros permitidos en la clase.
# Si se ingresa como Empleado al sistema solo se puede hacer ingreso a index y show de 
# liquidacion.
#
# Definición de la clase liquidacions_controller compuesta por
# * metodo index
# * metodo show
# * metodo new
# * metodo create
# * metodo update
# * metodo destroy
# * metodo authorize
# * set_liquidacion
# * liquidacion_params
class LiquidacionsController < ApplicationController
  before_action :authorize, except: [:index,:show]
  before_action :set_liquidacion, only: [:show, :edit, :update, :destroy]
  
  # Lista las liquidaciones pertenecientes solo a la persona que ingreso al sistema
  # en caso de ser Empleado, si es Administrador lista todas las liquidaciones existentes
  # en el sistema.
  def index
      @liquidacions = Liquidacion.all
      if current_user and current_user.tipo_usuario == "Administrador"
        if params[:start_period]
          @liquidacions = Liquidacion.search(params[:start_period], params[:end_period]).order("personal_id DESC")
        end
      elsif current_user
        @liquidacions = Liquidacion.where(personal_id: current_user.id)
        if params[:start_period]
          @liquidacions = Liquidacion.search(params[:start_period], params[:end_period]).order("personal_id DESC")
        end
      end
 end

  # Muestra la informacion de la liquidacion seleccionada, ademas pasa la misma informacion
  # a liquidacion.pdf
  def show
    @liquidacion = Liquidacion.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
      pdf = LiquidacionPdf.new(@liquidacion)
      send_data pdf.render, filename: "liquidacion #{@liquidacion.personal.nombre_apellido}.pdf",
                            type: "application/pdf",
                            disposition: "inline"
      end
    end
  end


  # GET /liquidacions/new
  def new
    @liquidacion = Liquidacion.new
  end

  # GET /liquidacions/1/edit
  def edit
  end

  # POST /liquidacions
  # POST /liquidacions.json
  def create
    
    @liquidacion = Liquidacion.new(liquidacion_params)

    respond_to do |format|
      if @liquidacion.save
        format.html { redirect_to @liquidacion, notice: 'Liquidacion fue creado exitosamente.' }
        format.json { render :show, status: :created, location: @liquidacion }
      else
        format.html { render :new }
        format.json { render json: @liquidacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /liquidacions/1
  # PATCH/PUT /liquidacions/1.json
  def update
    respond_to do |format|
      if @liquidacion.update(liquidacion_params)
        format.html { redirect_to @liquidacion, notice: 'Liquidacion fue actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @liquidacion }
      else
        format.html { render :edit }
        format.json { render json: @liquidacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /liquidacions/1
  # DELETE /liquidacions/1.json
  def destroy
    @liquidacion.destroy
    respond_to do |format|
      format.html { redirect_to liquidacions_url, notice: 'Liquidacion fue eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_liquidacion
      @liquidacion = Liquidacion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def liquidacion_params
      params.require(:liquidacion).permit(:asignacion_id, :habere_id, :bonificacion_id, :descuento_adicional_id, :personal_id, :fecha_pago, :porcentaje_afp, :descuento_afp, :descuento_isapre, :impuesto, :cotizacion_voluntaria, :horas_trabajadas, :remuneracion, :cantidad_horas_extra, :horas_extra, :vacaciones, :total_imponible, :sindicato, :total_haberes, :desc_legales, :desc_varios, :liquido_pagar, :asignacion_familiar)
    end
end

app/helpers/liquidacions_helper.rb
module LiquidacionsHelper
end

app/views/liquidacions/_form.html.erb
<%= form_for(@liquidacion) do |f| %>
  <% if @liquidacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@liquidacion.errors.count, "error") %> prohibited this liquidacion from being saved:</h2>

      <ul>
      <% @liquidacion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="large-4 columns">
    <div class="field">
      <%= f.label :"Categoria" %><br>
      <%= collection_select(nil, :categorium_id, Categorium.order(:categoria), :id, :categoria, include_blank: :true) %>
    </div> 
  </div>
  <div class="large-4 columns">
    <div class="field">
      <%= f.label :"Subcategoria" %><br>
      <%= grouped_collection_select(nil, :subcategorium_id, Categorium.order(:categoria), :subcategorium, :categoria, :id, :subcategoria, {include_blank: :true}) %>
    </div>
  </div>
  <div class="large-4 columns">
    <div class="field">
      <%= f.label :personal_id %><br>
      <%= grouped_collection_select(:liquidacion, :personal_id, Subcategorium.order(:subcategoria), :personal, :subcategoria, :id, :nombre_apellido, {include_blank: :true}) %> 
    </div>
  </div>
</div>

<script>
  var option_index = $("#liquidacion_personal_id option:selected").val();
  $('#liquidacion_descuento_isapre option').eq(option_index).prop('selected', true);
  $('#liquidacion_cotizacion_voluntaria option').eq(option_index).prop('selected', true);
  $('#_cargas_familiar option').eq(option_index).prop('selected', true);
  $('#_afp_id option').eq(option_index).prop('selected', true);
  $("#_sindicato option").eq(option_index).prop('selected', true);

//Listen for the change
  $('#liquidacion_personal_id').on('change', function(){
      option_index = $("#liquidacion_personal_id option:selected").val();
      $('#liquidacion_descuento_isapre option').eq(option_index).prop('selected', true);
      $('#liquidacion_cotizacion_voluntaria option').eq(option_index).prop('selected', true);
      $('#_cargas_familiar option').eq(option_index).prop('selected', true);
      $('#_afp_id option').eq(option_index).prop('selected', true);
      $("#_sindicato option").eq(option_index).prop('selected', true);
  });

</script>

<div class="row">
  <div class="large-4 columns">
    <div class="field">
      <%= f.label :"Sueldo base por hora trabajada" %><br>
      <%= grouped_collection_select(:liquidacion, :habere_id, Subcategorium.order(:subcategoria), :habere, :subcategoria, :id, :valor_hora, {include_blank: :true}) %>
    </div>
  </div>
  <div class="large-4 columns">
    <div class="field">
      <%= f.label :horas_trabajadas %><br>
      <%= f.text_field :horas_trabajadas %>
    </div>
  </div>
  <div class="large-4 columns">
    <div class="field">
      <%= f.label :remuneracion %><br>
      <%= f.number_field :remuneracion, :readonly => true %>
    </div>
  </div>
</div>

<div class="row">
  <div class="large-6 columns">
    <div class="field">
      <%= f.label :cantidad_horas_extra %><br>
      <%= f.text_field :cantidad_horas_extra %>
    </div>
  </div>
  <div class="large-6 columns">
    <div class="field">
      <%= f.label :horas_extra %><br>
      <%= f.text_field :horas_extra, :readonly => true %>
    </div>
  </div>
</div>
<hr>

<div class="row">
  <div class="large-6 columns">
    <div class="field">
      <%= f.label :asignacion_id %><br>
      <%= grouped_collection_select(:liquidacion, :asignacion_id, Subcategorium.order(:subcategoria), :asignacion, :subcategoria, :id, :asignacion, {include_blank: :true}) %>
    </div>
  </div>
  <div class="large-6 columns">
    <div class="field">
      <%= f.label :bonificacion_id %><br>
      <%= grouped_collection_select(:liquidacion, :bonificacion_id, Subcategorium.order(:subcategoria), :bonificacion, :subcategoria, :id, :bono, include_blank: :true) %>
    </div>
  </div>
</div>
<div class="row">  
  <div class="large-6 columns">
    <div class="field">
      <%= f.label :vacaciones %><br>
      <%= f.text_field :vacaciones %>
    </div>
  </div>
</div>
<div class="row">  
  <div class="large-6 columns">
    <div class="field">
      <%= f.label :total_imponible %><br>
      <%= f.text_field :total_imponible, :readonly => true  %>
    </div>
  </div>
  <div class="large-6 columns">
    <div class="field">
      <%= f.label :total_haberes %><br>
      <%= f.number_field :total_haberes, :readonly => true %>
    </div>
     
  </div>
</div>
<div class="row">  
  <div class="large-12 columns">
   <%= submit_tag "Calcular totales de haberes", type: 'button', id: 'calculoHaberes' %> 
  </div>
</div>
<hr>

<div class="row">
  <div class="large-3 columns">
  <%= hidden_field_tag "monto1", AsignacionFamiliar.where(id: 1).limit(1).pluck(:monto) %>
  <%= hidden_field_tag "monto2", AsignacionFamiliar.where(id: 2).limit(1).pluck(:monto) %>
  <%= hidden_field_tag "monto3", AsignacionFamiliar.where(id: 3).limit(1).pluck(:monto) %>
  <%= hidden_field_tag "monto4", AsignacionFamiliar.where(id: 4).limit(1).pluck(:monto) %>
  </div>
  <div class="large-3 columns">
  <%= hidden_field_tag "asignacion1", AsignacionFamiliar.where(id: 1).limit(1).pluck(:requisitoMaximo) %>
  <%= hidden_field_tag "asignacion2", AsignacionFamiliar.where(id: 2).limit(1).pluck(:requisitoMaximo) %>
  <%= hidden_field_tag "asignacion3", AsignacionFamiliar.where(id: 3).limit(1).pluck(:requisitoMaximo) %>
  <%= hidden_field_tag "topeslegales1", TopesLegale.where(id: 1).limit(1).pluck(:topemaximo) %>
  </div>
  <div class="large-3 columns">
  <%= hidden_field_tag "impuesto1", ImpuestoUnico.where(id: 1).limit(1).pluck(:imponibleMaximo) %>
  <%= hidden_field_tag "impuesto2", ImpuestoUnico.where(id: 2).limit(1).pluck(:imponibleMaximo) %>
  <%= hidden_field_tag "impuesto3", ImpuestoUnico.where(id: 3).limit(1).pluck(:imponibleMaximo) %>
  <%= hidden_field_tag "impuesto4", ImpuestoUnico.where(id: 4).limit(1).pluck(:imponibleMaximo) %>
  <%= hidden_field_tag "impuesto5", ImpuestoUnico.where(id: 5).limit(1).pluck(:imponibleMaximo) %>
  <%= hidden_field_tag "impuesto6", ImpuestoUnico.where(id: 6).limit(1).pluck(:imponibleMaximo) %>
  <%= hidden_field_tag "impuesto7", ImpuestoUnico.where(id: 7).limit(1).pluck(:imponibleMaximo) %>
  </div>
  <div class="large-3 columns">
  <%= hidden_field_tag "factor2", ImpuestoUnico.where(id: 2).limit(1).pluck(:factor) %>
  <%= hidden_field_tag "factor3", ImpuestoUnico.where(id: 3).limit(1).pluck(:factor) %>
  <%= hidden_field_tag "factor4", ImpuestoUnico.where(id: 4).limit(1).pluck(:factor) %>
  <%= hidden_field_tag "factor5", ImpuestoUnico.where(id: 5).limit(1).pluck(:factor) %>
  <%= hidden_field_tag "factor6", ImpuestoUnico.where(id: 6).limit(1).pluck(:factor) %>
  <%= hidden_field_tag "factor7", ImpuestoUnico.where(id: 7).limit(1).pluck(:factor) %>
  <%= hidden_field_tag "factor8", ImpuestoUnico.where(id: 8).limit(1).pluck(:factor) %>
  </div>
    <div class="large-3 columns">
  <%= hidden_field_tag "rebaja2", ImpuestoUnico.where(id: 2).limit(1).pluck(:rebaja) %>
  <%= hidden_field_tag "rebaja3", ImpuestoUnico.where(id: 3).limit(1).pluck(:rebaja) %>
  <%= hidden_field_tag "rebaja4", ImpuestoUnico.where(id: 4).limit(1).pluck(:rebaja) %>
  <%= hidden_field_tag "rebaja5", ImpuestoUnico.where(id: 5).limit(1).pluck(:rebaja) %>
  <%= hidden_field_tag "rebaja6", ImpuestoUnico.where(id: 6).limit(1).pluck(:rebaja) %>
  <%= hidden_field_tag "rebaja7", ImpuestoUnico.where(id: 7).limit(1).pluck(:rebaja) %>
  <%= hidden_field_tag "rebaja8", ImpuestoUnico.where(id: 8).limit(1).pluck(:rebaja) %>
  </div>
</div>

<div class="row">
  <div class="large-6 columns">
    <div class="field">
      <%= f.label :descuento_afp %><br>
      <%= f.number_field :descuento_afp, :readonly => true %>
    </div>
  </div>
  <div class="large-4 columns"style="display: none;">
    <div class="field">
      <%= f.label :porcentaje_afp %><br>
      <%= collection_select(nil, :afp_id, Personal.all, :afp_id, :id, {include_blank: :true}) %>
    </div>
  </div>
  <div class="large-4 columns"style="display: none;">
    <div class="field">
      <%= collection_select(:liquidacion, :porcentaje_afp, Afp.all, :descuento_afp, :id, {include_blank: :true}) %>
    </div>
  </div>

  <script>
    var option_index = $("#_afp_id option:selected").val();
    $('#liquidacion_porcentaje_afp option').eq(option_index).prop('selected', true);

    $('#liquidacion_personal_id').on('change', function(){
        option_index = $("#_afp_id option:selected").val();
        $('#liquidacion_porcentaje_afp option').eq(option_index).prop('selected', true);
    });
  </script>

</div>

<div class="row">
  <div class="large-6 columns" style="display: none;" >
    <div class="field">
      <%= f.label :cotizacion_voluntaria %><br>
      <%= collection_select(:liquidacion, :cotizacion_voluntaria, Personal.all, :cotizacion_voluntaria, :id, {include_blank: :true}) %> 
    </div>
  </div>
  <div class="large-6 columns" style="display: none;" > 
    <div class="field">
      <%= f.label :descuento_isapre %><br>
      <%= collection_select(:liquidacion, :descuento_isapre, Personal.all, :descuento_isapre, :id, {include_blank: :true}) %>
    </div>
  </div>
</div>  
 <div class="row">
  <div class="large-6 columns">
    <div class="field">
      <%= f.label :"Numero de cargas" %><br>
     <%= collection_select(nil, :cargas_familiar, Personal.all, :cargas_familiar, :cargas_familiar, {include_blank: :true}) %>
    </div>
  </div>
  <div class="large-6 columns">
    <div class="field">
      <%= f.label :asignacion_familiar %><br>
      <%= f.text_field :asignacion_familiar, :readonly => true %>
    </div>
  </div>
</div>
<div class="row">
  <div class="large-4 columns" style="display: none;">
    <div class="field">
      <%= collection_select(nil, :sindicato, Personal.all, :sindicato_id, :id, {include_blank: :true}) %>
    </div>
  </div>

  <div class="large-4 columns" style="display: none;">
    <div class="field">
      <%= f.label :sindicato %><br>
      <%= collection_select(:liquidacion, :sindicato, Sindicato.all, :cuota_sindical, :id, {include_blank: :true}) %>
    </div>
  </div>


  <script>
    var option_index = $("#_sindicato option:selected").val();
    $('#liquidacion_sindicato option').eq(option_index).prop('selected', true);

    $('#liquidacion_personal_id').on('change', function(){
        option_index = $("#_sindicato option:selected").val();
        $('#liquidacion_sindicato option').eq(option_index).prop('selected', true);
    });
  </script>

  <div class="large-6 columns">
    <div class="field">
      <%= f.label :impuesto %><br>
      <%= f.text_field :impuesto, :readonly => true  %>
      <%= submit_tag "Calcular Impuesto", type: 'button', id: 'impuesto' %> 
    </div>
  </div>
  <div class="large-6 columns">
    <div class="field">
      <%= f.label :descuento_adicional_id %><br>
      <%= collection_select(:liquidacion, :descuento_adicional_id, DescuentoAdicional.all, :id, :descuento_adicional, {include_blank: :true}) %>
    </div>
  </div>
</div> 

<div class="row">
  <div class="large-4 columns">
    <div class="field">
      <%= f.label :desc_legales %><br>
      <%= f.number_field :desc_legales, :readonly => true %>
    </div>
  </div>
  <div class="large-4 columns">
    <div class="field">
      <%= f.label :desc_varios %><br>
      <%= f.number_field :desc_varios, :readonly => true %>
    </div>
  </div>
  <div class="large-4 columns">
    <div class="field">
      <%= f.label :liquido_pagar %><br>
      <%= f.number_field :liquido_pagar, :readonly => true %>
    </div>
  </div>  
</div> 
<div class="row">  
  <div class="large-12 columns">
   <%= submit_tag "Calcular liquido a pagar", type: 'button', id: 'coffeeScript' %> 
  </div>
</div>
<hr>

  <div class="field">
    <%= f.label :fecha_pago %><br>
    <%= f.date_select :fecha_pago,{ start_year: DateTime.now.year+1, end_year: DateTime.now.year - 10, order: [:day, :month, :year], include_blank: true},:style => "width: 221px;"%>
  </div>
  

  <div class="actions">
    <%= f.submit ( f.object.new_record? ? "Crear" : "Actualizar"), class: "btn" %>
  </div>
<% end %>

app/views/liquidacions/edit.html.erb
<h3>Editando Liquidación</h3>

<%= render 'form' %>

<%= link_to 'Ver', @liquidacion %> |
<%= link_to 'Volver', liquidacions_path %>

app/views/liquidacions/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Listando Liquidaciones</h3>
<%= form_tag liquidacions_path, :method => "get", id: "search-form" do %>
<p>
<div class="row">
  <div class="large-4 columns">
    <div class="field">
      <%= text_field_tag :start_period, params[:start_period], placeholder: 'Fecha de Inicio'%>
    </div>
  </div>
  <div class="large-4 columns">
    <div class="field">
      <%= text_field_tag :end_period, params[:end_period], placeholder: 'Fecha de Termino' %>
    </div>
  </div>
  <div class="large-4 columns">
    <div class="field">
      <%= submit_tag "Buscar por fecha" %>
    </div>
  </div>
</div>

</p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Nombre de trabajador</th>
      <th>Asignación</th>
      <th>Sueldo base</th>
      <th>Bonificación</th>
      <th>Fecha pago</th>
      <th>Horas trabajadas</th>
      <th>Líquido pagar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @liquidacions.each do |liquidacion| %>
      <tr>
        <td><%= liquidacion.personal.nombre_apellido %></td>
        <td>$<%= number_to_currency(liquidacion.asignacion.asignacion,strip_insignificant_zeros: true, :unit => "") %></td>
        <td>$<%= number_to_currency(liquidacion.habere.valor_hora,strip_insignificant_zeros: true, :unit => "") %></td>
        <td>$<%= number_to_currency(liquidacion.bonificacion.bono,strip_insignificant_zeros: true, :unit => "") %></td>
        <td><%= liquidacion.fecha_pago.strftime("%d/%m/%Y")  %></td>
        <td><%= liquidacion.horas_trabajadas %></td>
        <td>$<%= number_to_currency(liquidacion.liquido_pagar,strip_insignificant_zeros: true, :unit => "" )%></td>
        <td><%= link_to 'Ver', liquidacion %></td>
        <%if current_user.tipo_usuario=="Administrador"%>
        <td><%= link_to 'Editar', edit_liquidacion_path(liquidacion) %></td>
        <td><%= link_to 'Eliminar', liquidacion, method: :delete, data: { confirm: '¿Esta seguro?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%if current_user.tipo_usuario=="Administrador"%>
<%= link_to 'Nueva Liquidacion', new_liquidacion_path %>
<%end%>

app/views/liquidacions/new.html.erb
<h3>Nueva Liquidación</h3>

<%= render 'form' %>

<%= link_to 'Volver', liquidacions_path %>

app/views/liquidacions/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <td>
    <p>
      <strong>Trabajador:</strong>
      <%= @liquidacion.personal.nombre_apellido %>
    </p>

    <p>
      <strong>Sueldo base:</strong>
      $<%= number_to_currency(@liquidacion.habere.valor_hora,strip_insignificant_zeros: true, :unit => "") %>
    </p>

    <p>
      <strong>Horas trabajadas:</strong>
      <%= @liquidacion.horas_trabajadas %>
    </p>

    <p>
      <strong>Remuneración:</strong>
      $<%= number_to_currency(@liquidacion.remuneracion,strip_insignificant_zeros: true, :unit => "") %>
    </p>
    <p>
      <strong>Cantidad horas extra:</strong>
      <%= @liquidacion.cantidad_horas_extra %>
    </p>

    <p>
      <strong>Horas extra:</strong>
      $<%= number_to_currency(@liquidacion.horas_extra,strip_insignificant_zeros: true, :unit => "") %>
    </p>

    <p>
    <%if @liquidacion.asignacion.asignacion != nil%>
      <strong>Asignación:</strong>
      $<%= number_to_currency(@liquidacion.asignacion.asignacion,strip_insignificant_zeros: true, :unit => "") %>
    <%end%>
    </p>

    <p>
    
      <strong>Asignación familiar:</strong>
      $<%= number_to_currency(@liquidacion.asignacion_familiar,strip_insignificant_zeros: true, :unit => "") %>
    
    </p>

    <p>
    <%if @liquidacion.bonificacion.bono != nil%>
      <strong>Bonificación:</strong>
      $<%= number_to_currency(@liquidacion.bonificacion.bono,strip_insignificant_zeros: true, :unit => "") %>
    <%end%>
    </p>

    <p>
      <strong>Vacaciones:</strong>
      $<%= number_to_currency(@liquidacion.vacaciones,strip_insignificant_zeros: true, :unit => "") %>
    </p>

    <p>
      <strong>Total imponible:</strong>
      $<%= number_to_currency(@liquidacion.total_imponible,strip_insignificant_zeros: true, :unit => "") %>
    </p>


    <p>
      <strong>Total haberes:</strong>
      $<%= number_to_currency(@liquidacion.total_haberes,strip_insignificant_zeros: true, :unit => "")%>
    </p>


    <p>
    <%if @liquidacion.descuento_adicional !=nil%>
      <strong>Descuento adicional:</strong>
      $<%= number_to_currency(@liquidacion.descuento_adicional.descuento_adicional,strip_insignificant_zeros: true, :unit => "") %>
    <%end%>
    </p>



  </td>

  <td>
    <p>
      <strong>Porcentaje afp:</strong>
      <%= @liquidacion.porcentaje_afp %>%
    </p>

    <p>
      <strong>Descuento afp:</strong>
      $<%= number_to_currency(@liquidacion.descuento_afp,strip_insignificant_zeros: true, :unit => "") %>
    </p>
    <p>
      <strong>Descuento isapre:</strong>
      $<%= number_to_currency(@liquidacion.descuento_isapre,strip_insignificant_zeros: true, :unit => "") %>
    </p>

    <p>
      <strong>Sindicato:</strong>
      $<%= number_to_currency(@liquidacion.sindicato,strip_insignificant_zeros: true, :unit => "") %>
    </p>

    <p>
      <strong>Impuesto:</strong>
      $<%= number_to_currency(@liquidacion.impuesto,strip_insignificant_zeros: true, :unit => "") %>
    </p>

    <p>
      <strong>Cotización voluntaria:</strong>
      $<%= number_to_currency(@liquidacion.cotizacion_voluntaria,strip_insignificant_zeros: true, :unit => "") %>
    </p>

    <p>
      <strong>Total desc. legales:</strong>
      $<%= number_to_currency(@liquidacion.desc_legales,strip_insignificant_zeros: true, :unit => "") %>
    </p>

    <p>
      <strong>Total desc. varios:</strong>
      $<%= number_to_currency(@liquidacion.desc_varios,strip_insignificant_zeros: true, :unit => "") %>
    </p>

    <p>
      <strong>Líquido pagar:</strong>
      $<%= number_to_currency(@liquidacion.liquido_pagar,strip_insignificant_zeros: true, :unit => "") %>
    </p>

    <p>
      <strong>Fecha pago:</strong>
      <%= @liquidacion.fecha_pago.strftime("%d/%m/%Y") %>
    </p>

  </td>
</table>

<p>
<%= link_to "Liquidacion en pdf", liquidacion_path(@liquidacion, format: "pdf")%>
</p>

<%if current_user.tipo_usuario=="Administrador"%>
<%= link_to 'Editar', edit_liquidacion_path(@liquidacion) %>|
<%end%>
<%= link_to 'Volver', liquidacions_path %>